"""followers

Revision ID: 103fc51dc2ab
Revises: a6dba379ed26
Create Date: 2020-08-15 21:00:05.963145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103fc51dc2ab'
down_revision = 'a6dba379ed26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
